BLOCK_CHAIN = None
BLOCK_CHAIN_LOCK = None

PEERS_NUM = 0
IS_MAIN = False

HEART_BEAT_CNT = 0
UNIFORM_CNT = 0

SEND_CNT = 0
SEND_CNT_LOCK = None

PRE_UNIFORM_CNT = 0
PRE_UNIFORM_CNT_LOCK = None

RECV_BUF = []
RECV_IS_LOCK = False

UNIFORM_HASH_BUFF = []
UNIFORM_HASH_BUFF_LOCK = None

UNIFORM_DIFF_HASH_URLS = []